# Generated by Django 4.2.7 on 2023-12-07 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cienciaficcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=40)),
                ('año', models.IntegerField()),
                ('director', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Comedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=40)),
                ('año', models.IntegerField()),
                ('director', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Terror',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=40)),
                ('año', models.IntegerField()),
                ('director', models.CharField(max_length=40)),
            ],
        ),
    ]
